baseURL = "https://lifecoretransformation.com"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Life Core Transformation Workshop"
theme = "meghna-hugo"
summaryLength = 10

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Jadwal"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Testimoni"
    URL = "testimoni"
    weight = 4

    [[menu.nav]]
    name = "Trainer"
    URL = "trainer"
    weight = 5

#    [[menu.nav]]
#    name = "Pricing"
#    URL = "pricing"
#    weight = 6

#    [[menu.nav]]
#    name = "Blog"
#    URL = "blog"
#    weight = 7

#    [[menu.nav]]
#    name = "Contact"
#    URL = "contact-us"
#    weight = 8

# Site params
[params]
home= "Home"
logo = "images/logo.png"
#gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Reborn To Be The Champion"
author = "Irfan"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/liveacara.jpg"
    icon = "tf-ion-play"
    #heading = "Experience the new Platform"
    content= "Anda Benar-benar Mau Mempelajari Teknologi Pikiran Terbaru dan Tercanggih untuk"
    contentSpan = "MERAIH, MEMPERCEPAT"
    contentDan = "dan"
    contentSpanLagi = "MEMPERBESAR KESUKSESAN"
    contentAnda = "Anda"
    videoUrl = "https://www.youtube.com/embed/COsrVyYaCXI"
    btn = true
    btnText="Explore Me"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = true
    title = "Ya!! Saya Mau Daftar"
    content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis tenetur odio impedit incidunt? Omnis accusantium ea reiciendis, fugit commodi nostrum."
    btnURL = "https://s.id/MCLCTW"
    btnText = "PENDAFTARAN"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Alumni"
        icon = "tf-ion-android-happy"
        count = "1000+"

        [[params.counter.counterItem]]
        title = "Event"
        icon = "tf-ion-android-calendar"
        count = "50+"

        [[params.counter.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "100+"

        [[params.counter.counterItem]]
        title = "Kota"
        icon = "tf-ion-android-home"
        count = "3+"

    # footer
    [params.footer]
        copyright = "AHI"
        copyrightURL = "https://www.ariesandi.com"
        hati = "tf-ion-heart"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "https://www.facebook.com/AriesandiCht/"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "https://twitter.com/AriesandiCHt"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "https://www.youtube.com/c/AriesandiCHt"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-instagram"
        url = "https://www.instagram.com/ariesandi_setyono/"
